---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=auto              # optional
      - SERVERPORT=15555            # optional
      # - PEERS=1                   # optional
      # - PEERDNS=auto              # optional
      - INTERNAL_SUBNET=10.13.13.0  # optional
      - ALLOWEDIPS=0.0.0.0/0        # optional
      - LOG_CONFS=true              # optional
    volumes:
      - /opt/wireguard/volumes/config:/config
      - /lib/modules:/lib/modules
    networks:
      - wireguard
    ports:
      - 15555:15555/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET=secret_to_replace    # replace
      - WGUI_USERNAME=username_to_replace   # replace
      - WGUI_PASSWORD=password_to_replace   # replace
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 5000:5000
    networks:
      - wireguard
    volumes:
      - /opt/wireguard/volumes/db:/app/db
      - /opt/wireguard/volumes/config:/etc/wireguard

networks:
  wireguard:
